/**
 * Created by vtdien on 12/17/2017.
 */

//ACCOUNT
export const RECEIVE_POST_LOGIN_TODO = 'LOGIN_TODO';
export const RECEIVE_POST_REGISTER_TODO =  'REGISTER_TODO';
export const RECEIVE_POST_SEARCH_BALANCE_TODO = 'SEARCH_BALANCE_TODO';

//TRANSACTION
export const RECEIVE_GET_SEARCH_ALL_TODO = 'GET_SEARCH_ALL_TODO';
export const RECEIVE_GET_SEARCH_TODO = 'GET_SEARCH_TODO';
export const RECEIVE_POST_TRANSACT_TODO = 'POST_TRANSACT_TODO';

//DEFAULT
export const REQUEST_POST_TODO = 'REQUEST_POST_TODO';

export const LOG_OUT_TODO = 'LOG_OUT_TODO';